"""initial schema (06_erd_database_design.md + price_snapshots, audit_logs)

Revision ID: 44a22f3b90df
Revises:
Create Date: 2026-09-24 11:20:43.239339

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "44a22f3b90df"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "audit_logs",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("event_type", sa.String(length=64), nullable=False),
        sa.Column("actor_id", sa.UUID(), nullable=True),
        sa.Column("entity_type", sa.String(length=64), nullable=True),
        sa.Column("entity_id", sa.String(length=64), nullable=True),
        sa.Column(
            "data",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_audit_created", "audit_logs", ["created_at"], unique=False)
    op.create_index("idx_audit_event_type", "audit_logs", ["event_type"], unique=False)
    op.create_table(
        "price_snapshots",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("fetched_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("xau_usd_per_ounce", sa.Numeric(precision=12, scale=4), nullable=False),
        sa.Column("usd_iqd", sa.Numeric(precision=12, scale=4), nullable=False),
        sa.Column("gold_24k_iqd_per_gram", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("source", sa.String(length=32), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_price_snapshots_fetched_at", "price_snapshots", ["fetched_at"], unique=False
    )
    op.create_table(
        "users",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("role", sa.Enum("investor", "seller", name="user_role"), nullable=False),
        sa.Column("full_name", sa.String(length=255), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column("kyc_verified", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column(
            "risk_profile", sa.Enum("low", "medium", "high", name="risk_profile"), nullable=True
        ),
        sa.Column(
            "subscription_tier",
            sa.Enum("free", "premium", name="subscription_tier"),
            server_default="free",
            nullable=False,
        ),
        sa.Column("subscription_expiry_date", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_users_email", "users", ["email"], unique=True)
    op.create_index("idx_users_role", "users", ["role"], unique=False)
    op.create_index("idx_users_sub_expiry", "users", ["subscription_expiry_date"], unique=False)
    op.create_table(
        "asset_listings",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("seller_id", sa.UUID(), nullable=False),
        sa.Column("total_weight_grams", sa.Numeric(precision=10, scale=3), nullable=False),
        sa.Column("available_weight_grams", sa.Numeric(precision=10, scale=3), nullable=False),
        sa.Column("karat", sa.SmallInteger(), nullable=False),
        sa.Column("base_price_per_gram", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column(
            "status",
            sa.Enum("active", "sold_out", "suspended", name="listing_status"),
            server_default="active",
            nullable=False,
        ),
        sa.Column("is_promoted", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("promotion_expiry_date", sa.DateTime(timezone=True), nullable=True),
        sa.Column("idempotency_key", sa.String(length=128), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "available_weight_grams <= total_weight_grams", name="ck_listings_available_le_total"
        ),
        sa.CheckConstraint(
            "available_weight_grams >= 0", name="ck_listings_available_non_negative"
        ),
        sa.CheckConstraint("karat IN (18, 21, 22, 24)", name="ck_listings_karat"),
        sa.CheckConstraint("total_weight_grams > 0", name="ck_listings_total_positive"),
        sa.ForeignKeyConstraint(["seller_id"], ["users.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_listings_promoted",
        "asset_listings",
        ["is_promoted", "promotion_expiry_date"],
        unique=False,
    )
    op.create_index("idx_listings_seller", "asset_listings", ["seller_id"], unique=False)
    op.create_index("idx_listings_status", "asset_listings", ["status"], unique=False)
    op.create_index(
        "uq_listings_seller_idempotency",
        "asset_listings",
        ["seller_id", "idempotency_key"],
        unique=True,
    )
    op.create_table(
        "fractional_ownership_records",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("investor_id", sa.UUID(), nullable=False),
        sa.Column(
            "total_accumulated_grams",
            sa.Numeric(precision=12, scale=3),
            server_default=sa.text("0"),
            nullable=False,
        ),
        sa.Column("digital_signature_token", sa.String(length=512), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("total_accumulated_grams >= 0", name="ck_ownership_non_negative"),
        sa.ForeignKeyConstraint(["investor_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_ownership_investor", "fractional_ownership_records", ["investor_id"], unique=True
    )
    op.create_table(
        "transactions",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("investor_id", sa.UUID(), nullable=False),
        sa.Column("asset_id", sa.UUID(), nullable=False),
        sa.Column("purchased_weight_grams", sa.Numeric(precision=10, scale=3), nullable=False),
        sa.Column("execution_price_per_gram", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("principal_amount", sa.Numeric(precision=16, scale=2), nullable=False),
        sa.Column("commission_rate", sa.Numeric(precision=5, scale=4), nullable=False),
        sa.Column("commission_amount", sa.Numeric(precision=16, scale=2), nullable=False),
        sa.Column("total_paid_by_investor", sa.Numeric(precision=16, scale=2), nullable=False),
        sa.Column("idempotency_key", sa.String(length=128), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("purchased_weight_grams > 0", name="ck_tx_purchased_positive"),
        sa.ForeignKeyConstraint(["asset_id"], ["asset_listings.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["investor_id"], ["users.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_tx_asset", "transactions", ["asset_id"], unique=False)
    op.create_index("idx_tx_created", "transactions", ["created_at"], unique=False)
    op.create_index("idx_tx_investor", "transactions", ["investor_id"], unique=False)
    op.create_index(
        "uq_tx_investor_idempotency",
        "transactions",
        ["investor_id", "idempotency_key"],
        unique=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("uq_tx_investor_idempotency", table_name="transactions")
    op.drop_index("idx_tx_investor", table_name="transactions")
    op.drop_index("idx_tx_created", table_name="transactions")
    op.drop_index("idx_tx_asset", table_name="transactions")
    op.drop_table("transactions")
    op.drop_index("idx_ownership_investor", table_name="fractional_ownership_records")
    op.drop_table("fractional_ownership_records")
    op.drop_index("uq_listings_seller_idempotency", table_name="asset_listings")
    op.drop_index("idx_listings_status", table_name="asset_listings")
    op.drop_index("idx_listings_seller", table_name="asset_listings")
    op.drop_index("idx_listings_promoted", table_name="asset_listings")
    op.drop_table("asset_listings")
    op.drop_index("idx_users_sub_expiry", table_name="users")
    op.drop_index("idx_users_role", table_name="users")
    op.drop_index("idx_users_email", table_name="users")
    op.drop_table("users")
    op.drop_index("idx_price_snapshots_fetched_at", table_name="price_snapshots")
    op.drop_table("price_snapshots")
    op.drop_index("idx_audit_event_type", table_name="audit_logs")
    op.drop_index("idx_audit_created", table_name="audit_logs")
    op.drop_table("audit_logs")
    for enum_name in ("listing_status", "subscription_tier", "risk_profile", "user_role"):
        sa.Enum(name=enum_name).drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
